language: go

go:
  - 1.14

install:
  - export GOPATH=$HOME/gopath/src/github.com/latesun/filestore-server
  - export GOBIN=$HOME/gopath/src/github.com/latesun/filestore-server/bin
  - go mod tidy

script:
  - echo "test"
